### ISSUE TITLE
Headers-first support?

### ISSUE THREAD

**Issue by Kroese** [piotrnar/gocoin#10]
I was wondering how efficiently this client syncs. 

  - Does it implement header-first download?
  - Does it download headers from multiple peers simultanously?

**Comment by piotrnar** [comment]
Currently there is a a separate app "downloader" for the headers-first syncing. It's been a plan to build it into the client, but I had not time to work on it recently.
Anyway, the downloader is very efficient, but it also needs a lot of RAM to fetch the entire chain in one go (8GB should do).

And no - it does not download headers from multiple peers simultaneously, but in practice it doesn't really matter as downloading of all the headers from a single peer take a couple of minutes at most.

Please use the forum thread for this kind of questions: https://bitcointalk.org/index.php?topic=199306.0
