### ISSUE TITLE
[BUG] panic when first time run client. You didn't create dir before Creating empty default wallet

### ISSUE THREAD

**Issue by feeling4t** [piotrnar/gocoin#11]
go version go1.3.1 linux/amd64
Gocoin client version 1.0.3

in client/init.go, line 78~79
			fmt.Println("Creating empty default wallet at", default_wallet_fn)
			ioutil.WriteFile(default_wallet_fn, []byte(fmt.Sprintln("# Put your wallet's public addresses here")), 0660)

You didn't make dir before write file. Obviously, ioutil.WriteFile will fail, but you ignore the error.

feeling4t@feeling4t-laptop:~/btc/gocoin/client$ ./client -t
Gocoin client version 1.0.3
You seem to be running Gocoin for the fist time on this PC
/home/feeling4t/.bitcoin/gocoin/tstnet/wallet/DEFAULT not found
Creating empty default wallet at /home/feeling4t/.bitcoin/gocoin/tstnet/wallet/DEFAULT
Place secrets of your stealth keys in /home/feeling4t/.bitcoin/gocoin/tstnet/wallet/stealth/  (use 'arm' to load more)
main panic recovered: runtime error: invalid memory address or nil pointer dereference
/home/feeling4t/btc/gocoin/client/main.go:250 (0x40709f)
	func.002: fmt.Println(string(debug.Stack()))
/usr/local/go/src/pkg/runtime/panic.c:248 (0x415b6d)
	panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
/usr/local/go/src/pkg/runtime/panic.c:552 (0x41661d)
	panicstring: runtime·panic(err);
/usr/local/go/src/pkg/runtime/os_linux.c:237 (0x41520e)
	sigpanic: runtime·panicstring("invalid memory address or nil pointer dereference");
/home/feeling4t/gowork/src/github.com/piotrnar/gocoin/client/wallet/balance.go:517 (0x4a338f)
	LoadAllWallets: for i := range MyWallet.Addrs {
/home/feeling4t/btc/gocoin/client/init.go:88 (0x401c0f)
	host_init: wallet.LoadAllWallets()
/home/feeling4t/btc/gocoin/client/main.go:260 (0x406089)
	main: host_init() // This will create the DB lock file and keep it open
/usr/local/go/src/pkg/runtime/proc.c:247 (0x417bca)
	main: main·main();
/usr/local/go/src/pkg/runtime/proc.c:1445 (0x41a390)
	goexit: runtime·goexit(void)

Closing network

modify it to 

			fmt.Println("Creating empty default wallet at", default_wallet_fn)
			if err := ioutil.WriteFile(default_wallet_fn, []byte(fmt.Sprintln("# Put your wallet's public addresses here")), 0660); err !=nil {
				fmt.Println("###Create wallet error:", err)
			}else{
				fmt.Println("###Create wallet OK")
			}

feeling4t@feeling4t-laptop:~/btc/gocoin/client$ ./client -t
Gocoin client version 1.0.3
You seem to be running Gocoin for the fist time on this PC
/home/feeling4t/.bitcoin/gocoin/tstnet/wallet/DEFAULT not found
Creating empty default wallet at /home/feeling4t/.bitcoin/gocoin/tstnet/wallet/DEFAULT
###Create wallet error: open /home/feeling4t/.bitcoin/gocoin/tstnet/wallet/DEFAULT: no such file or directory
Place secrets of your stealth keys in /home/feeling4t/.bitcoin/gocoin/tstnet/wallet/stealth/  (use 'arm' to load more)
main panic recovered: runtime error: invalid memory address or nil pointer dereference
/home/feeling4t/btc/gocoin/client/main.go:250 (0x40709f)
	func.002: fmt.Println(string(debug.Stack()))
/usr/local/go/src/pkg/runtime/panic.c:248 (0x415b6d)
	panic: runtime·newstackcall(d->fn, (byte*)d->args, d->siz);
/usr/local/go/src/pkg/runtime/panic.c:552 (0x41661d)
	panicstring: runtime·panic(err);
/usr/local/go/src/pkg/runtime/os_linux.c:237 (0x41520e)
	sigpanic: runtime·panicstring("invalid memory address or nil pointer dereference");
/home/feeling4t/gowork/src/github.com/piotrnar/gocoin/client/wallet/balance.go:517 (0x4a338f)
	LoadAllWallets: for i := range MyWallet.Addrs {
/home/feeling4t/btc/gocoin/client/init.go:88 (0x401c0f)
	host_init: wallet.LoadAllWallets()
/home/feeling4t/btc/gocoin/client/main.go:260 (0x406089)
	main: host_init() // This will create the DB lock file and keep it open
/usr/local/go/src/pkg/runtime/proc.c:247 (0x417bca)
	main: main·main();
/usr/local/go/src/pkg/runtime/proc.c:1445 (0x41a390)
	goexit: runtime·goexit(void)

Closing network

**Comment by piotrnar** [comment]
Thank you for reporting. 

It's fixed now - 1.0.3 has been tagged.

The folder was being created, but then removed by os.RemoveAll(common.GocoinHomeDir)

Sorry - didn't run it on a fresh disk for while.
