### ISSUE TITLE
Source code not signed

### ISSUE THREAD

**Issue by marmarek** [piotrnar/gocoin#16]
Currently there is no way to verify if the downloaded source code is really what you've written. Please add pgp signatures. For example, at very least, sign release tags (`git tag -s ...`). But better - sign every commit (`gpg config commit.gpgsign true`, or `git commit -S`).

Other than that, the project looks really great! Really offline wallet!

**Comment by piotrnar** [comment]
Thanks. I will look into it.

**Comment by piotrnar** [comment]
OK. It took awhile but you can try already `git verify-tag 1.9.4`
