### ISSUE TITLE
importblocks.go error

### ISSUE THREAD

**Issue by Azulan** [piotrnar/gocoin#23]
I get the following when trying to build the import tool.

>#command-line-arguments
>.\importblocks.go:98: chain.Save undefined (type *chain.Chain has no field or method Save)

**Comment by piotrnar** [comment]
Thanks for reporting.
Try now.

**Comment by Azulan** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x506e47]

goroutine 1 [running]:
github.com/piotrnar/gocoin/lib/chain.NewChainExt(0xc04200e540, 0x3a, 0xc04200298
0, 0xc042048500, 0x0, 0x0)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/lib/chain/chain.go
:84 +0x177
github.com/piotrnar/gocoin/lib/chain.NewChain(0xc04200e540, 0x3a, 0xc042002980,
0xc042048500, 0x50)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/lib/chain/chain.go
:53 +0x58
main.import_blockchain(0xc04200e280, 0x32)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/tools/importblocks
.go:40 +0x9b
main.main()
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/tools/importblocks
.go:174 +0x82b

**Comment by piotrnar** [comment]
I'm sorry. 

I haven't used this tool for years. 
I don't even have the satoshi's blocks database now, to test it with.

**Comment by piotrnar** [comment]
Can you please try again, with the updated gocoin/lib/chain/chain.go ?

**Comment by piotrnar** [comment]
Could you please confirm if "importblocks" tool works fine for you now?
So I can close this issue...

**Comment by Azulan** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x506e47]

goroutine 1 [running]:
github.com/piotrnar/gocoin/lib/chain.NewChainExt(0xc04200e540, 0x3a, 0xc04200298
0, 0xc042048500, 0x0, 0x0)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/lib/chain/chain.go
:84 +0x177
github.com/piotrnar/gocoin/lib/chain.NewChain(0xc04200e540, 0x3a, 0xc042002980,
0xc042048500, 0x50)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/lib/chain/chain.go
:53 +0x58
main.import_blockchain(0xc04200e280, 0x32)
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/tools/importblocks
.go:40 +0x9b
main.main()
        C:/Users/-/Go/src/github.com/piotrnar/gocoin/tools/importblocks
.go:174 +0x82b

**Comment by Azulan** [comment]
Trying to build importchain now gives this error:

# command-line-arguments
.\importblocks.go:40: undefined: chain.NewChain\

**Comment by piotrnar** [comment]
You need to checkout the new version of importblocks.go

It doesn't use chain.NewChain anymore, but chain.NewChainExt instead.

**Comment by piotrnar** [comment]
I'm closing this issue, since there have been no more comments.
