### ISSUE TITLE
Can't build the GoCoin tools? (go build says "too many errors")

### ISSUE THREAD

**Issue by SuperHenkie** [piotrnar/gocoin#29]
I am trying to install GoCoin on a new Ubuntu 17.10 Server environment (with plenty of memory and disk space). Here's what I did:

1. install Go: `sudo apt install golang-go`
(after installation, `go version` says: `go version go1.8.3 linux/amd64`)

2. retrieved the GoCoin sources: `go get github.com/piotrnar/gocoin`

3. run `go build` in `~/go/src/github.com/piotrnar/gocoin/client` which seems to work OK

4. run `go build` in `~/go/src/github.com/piotrnar/gocoin/client` which gives:

```# github.com/piotrnar/gocoin/tools
./balio.go:5: binary redeclared in this block
	previous declaration at ./base58.go:15
./base58.go:19: main redeclared in this block
	previous declaration at ./balio.go:151
./bdb.go:7: binary redeclared as imported package name
	previous declaration at ./base58.go:15
./bdb.go:181: main redeclared in this block
	previous declaration at ./base58.go:19
./bootdat_qt.go:45: main redeclared in this block
	previous declaration at ./bdb.go:181
./btcversig.go:11: ltc redeclared as imported package name
	previous declaration at ./balio.go:24
./btcversig.go:21: help redeclared in this block
	previous declaration at ./base58.go:16
./btcversig.go:26: main redeclared in this block
	previous declaration at ./bootdat_qt.go:45
./compressdb.go:13: main redeclared in this block
	previous declaration at ./btcversig.go:26
./fetchblock.go:13: main redeclared in this block
	previous declaration at ./compressdb.go:13
./fetchblock.go:13: too many errors


Am I doing something wrong?

**Comment by piotrnar** [comment]
For the tools, you have to build each source file separately.

Just follow the instructions from the master README.md file:

------------------------------
## Tools
Go to the `tools/` folder and execute:

	go build btcversig.go

Repeat the `go build` for each source file of the tool you want to build.
