### ISSUE TITLE
How to use it for Litecoin

### ISSUE THREAD

**Issue by tapir** [piotrnar/gocoin#30]
```go
// Specify blocks directory
BlockDatabase := chain.NewBlockDB("/home/tapir/.litecoin/blocks")

h, _ := hex.DecodeString("892559879b5d0d8c3cbe37397772ad887158d85c79fb70d46fe6097fda1b9d82")
hash := btc.NewUint256(h)

d, t, err := BlockDatabase.BlockGet(hash)
if err != nil {
	oanic(err)
}
```

gives an error

```
Using malloc() for UTXO memory bindings
Block not in the index
```

eventhough it's a valid block.

**Comment by piotrnar** [comment]
I'm guessing it gives the error, because the block is not in the index. :)

**Comment by tapir** [comment]
It is in the index though

**Comment by piotrnar** [comment]
Impossible. 
For the block to be in the index, gocoin client would have to put it in there first.
But gocoin client does not support Litecoin and cannot connect to Litecoin network, so there is no way it had put a Litecoin block(s) in the BlockDB folder you pointed it to.
