### ISSUE TITLE
Error when start wallet "ERROR: open balance/unspent.txt: no such file or directory"

### ISSUE THREAD

**Issue by Gelembjuk** [piotrnar/gocoin#31]
Hi,
I try to run your application.
I want to understand how bitcoing works.
I compiled wallet and executed

Got output

```
$ ./wallet 
Gocoin Wallet version 1.9.3
This program comes with ABSOLUTELY NO WARRANTY

Using config file wallet.cfg
Seed file .secret not found
Enter your wallet's seed password: 
ERROR: open balance/unspent.txt: no such file or directory 
```

Did i do something wrong?  or it is expected behavior and i have todo something before to run it?

**Comment by piotrnar** [comment]
Yes, it is an expected behaviour.

See the user manual for more info on how to use it.

http://gocoin.pl/gocoin_manual.html
