### ISSUE TITLE
Broken private key padding

### ISSUE THREAD

**Issue by awsum** [piotrnar/gocoin#32]
`HDWallet.Child` is not guaranteed to always return 33-byte private key.
Also your PR policy is absurd. You'd better but that disclaimer in bold on top of the readme, so no one will waste time on it.

**Comment by piotrnar** [comment]
Sorry, have I asked you to waste any time on anything. I seriously don't remember.

If you want me to fix some issue with the code, try to be more specific about it.

**Comment by piotrnar** [comment]
OK, I think I know what you mean.

**Comment by piotrnar** [comment]
It's fixed now, however...

This fix may affect gocoin type 4 wallets, which had already been generated.

**If anyone has issues spending coins from gocoin wallet type 4 (generated with pre-1.9.4 version of gocoin wallet), please use wallet version 1.9.3 to sign your transaction.**

**Comment by piotrnar** [comment]
Thank you for reporting.
