### ISSUE TITLE
definitely bad

### ISSUE THREAD

**Issue by alexeyneu** [piotrnar/gocoin#39]
https://github.com/piotrnar/gocoin/blob/64a894a2babf2a97b9909381e46d8215607e0294/client/rpcapi/rpcapi.go#L35  
exactly this line and approach itself  
i'm C programmer and just examine go for now. in C i've done this stuff with sockets only(after some research).  
what stops you from doin it over http request engine? only two unusual things there are http auth(drags in base64 stuff with tricks needed)  and that thing that json part hooks in as a binary block. Latter is np to implement ,just unexpected  
C sample is here https://github.com/alexeyneu/json-demo/blob/master/json_c.cpp

**Comment by piotrnar** [comment]
This is just a test code that isn't used anywhere by the actual client.

I keep it there because maybe it will come handy one day again, when I go back to developing RPC.
