### ISSUE TITLE
How to use wallet binary?

### ISSUE THREAD

**Issue by inliquid** [piotrnar/gocoin#40]
Sorry but what does it mean? It's very first run. 
```
Gocoin Wallet version 1.9.5
This program comes with ABSOLUTELY NO WARRANTY

GOCOIN_WALLET_CONFIG not set
Using config file wallet.cfg
Seed file .secret not found
Enter your wallet's seed password: ***
ERROR: open balance/unspent.txt: The system cannot find the path specified.
```
Am I supposed to make some thing prior to running `wallet`? Where can I see some documentation?

**Comment by piotrnar** [comment]
It's not a GUI program - it isn't going to show you any window.

The documentation is on gocoin.pl - for example:
https://gocoin.pl/gocoin_manual_wallet.html
https://gocoin.pl/gocoin_manual_spending.html

**Comment by inliquid** [comment]
Nice joke, I read all your site prior to compile it. So what am I supposed to do to be able to generate few deterministic wallet addresses?

**Comment by piotrnar** [comment]
`wallet -l` ?

If you don't understand my manual, what makes you think that you can understand anything I tell you here?

**Comment by inliquid** [comment]
Because I pointed to specific step and specific error?
```
ERROR: open balance/unspent.txt: The system cannot find the path specified.
```

**Comment by piotrnar** [comment]
What do you think it means?

You're trying to check the balance of your wallet, while not having the balance folder where it looks for it.

Again: https://gocoin.pl/gocoin_manual_spending.html  - start form step number 1.

**Comment by inliquid** [comment]
What shall I think?
Command help:
```
  -l    List public addressses from the wallet
```
But i didn't want to **list**. I just wanted to **created** and was expecting that very first run + password prompt means it will save newly generated addreses for me. That's why this message about unspent balance was really confusing.

**Comment by piotrnar** [comment]
Wallet is created each time you enter the password - but only in memory.
The only way to have it saved is to "list" it.

**Comment by inliquid** [comment]
I see now, Thank you.

**Comment by piotrnar** [comment]
In general it isn't meant to be executed without any command line switches.

Specifically so people don't run it without thinking.
