### ISSUE TITLE
Litecoin M-address support

### ISSUE THREAD

**Issue by inliquid** [piotrnar/gocoin#41]
Right now it's possible to generate 3* segwit addresses for Litecoin, however Litecoin core client switched to M* addresses to not confuse with Bitcoin. Will it be possible to generate M* addresses with gocoin wallet app?

**Comment by piotrnar** [comment]
OK - I will change it to M-address type for Litecoin.

However Litecoin suport in the wallet is very old and segwit support for Litecoin has never been tested, so be careful with it.

**Comment by inliquid** [comment]
Thanks!
