### ISSUE TITLE
 How can I try to mine with gocoin?

### ISSUE THREAD

**Issue by show-rosarugosa** [piotrnar/gocoin#42]
I want to try to understand how gocoin mines. Which part of the code should I check? Is gocoin still supporting mining?

**Comment by piotrnar** [comment]
There a bitcoind compatible JSON-RPC API

https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

But not all of it - only the functions that were needed to mine with some specific mining setup. 
You turn on the JSON-RPC by setting config value RPC.Enabled to true.

The code that implements it, is in gocoin/client/rpcapi

AFAIK it isn't working now as the API is missing some field needed for mining segwit blocks.
It should work though, if you don't include any segwit transactions inside blocks.
