### ISSUE TITLE
sign transaction and broadcast

### ISSUE THREAD

**Issue by huahuayu** [piotrnar/gocoin#43]
Hi, sorry for raise this issue, I just want to know how can I use gocoin to sign transaction and broadcast? especially when the account have muti utxos

**Comment by piotrnar** [comment]
It's described in the manual: https://gocoin.pl/gocoin_manual_spending.html

**Comment by huahuayu** [comment]
@piotrnar thank you! you reply so fast

**Comment by piotrnar** [comment]
Let me know if anything wasn't clear enough.
