### ISSUE TITLE
add config parameter for last trusted block

### ISSUE THREAD

**Issue by jlopp** [piotrnar/gocoin#45]
it would be helpful if there was a config parameter that makes it easy to set the trusted block to the genesis block. Something similar to Bitcoin Core's "assumevalid=0"

**Comment by piotrnar** [comment]
It's already there.
See `LastTrustedBlock`

**Comment by piotrnar** [comment]
Oh, you can change the value of the last trusted block while the node is running and the block chain is being synchronized. Just click on the hourglass icon inside the web interface.

**Comment by jlopp** [comment]
Ah, I only saw it in config.go but now I see that is also parses values from a (JSON?) config file. I'm trying to figure out where that file is suppose to be and what the format is - is there documentation for that?

**Comment by piotrnar** [comment]
The JSON file is called `gocoin.conf` and it is in the `client/` folder.

It is automatically created (with default values) when you start the client for the first time.

Documentation is here: https://gocoin.pl/gocoin_manual_config.html
