### ISSUE TITLE
Question about addr handling

### ISSUE THREAD

**Issue by amitiuttarwar** [piotrnar/gocoin#57]
Hi! I'm proposing some changes to `addr` handling in Bitcoin Core, and trying to ensure there will not be negative consequences for other clients on the network. For more information about the changes, please see my [mailing list post](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-April/018784.html). The crux is that, if the changes are accepted, bitcoin core would stop sending `addr` messages to inbound peers who don't "indicate interest" aka initiate an addr-related message (addr, addrv2, getaddr, or sendaddrv2). 

I'd like to ensure that gocoin clients will initiate an addr related message to outbound peers. I've looked in the code and believe the software plays nice, and am looking for a +1 from someone more familiar with this project. 

My understanding: in response to a `version` message, a gocoin node will self-advertise its address ([link](https://github.com/piotrnar/gocoin/blob/ec4713336ba8bac5a9c0b87992cb5ef40baa4741/client/network/tick.go#L708)), and often initiate a `getaddr` message ([link](https://github.com/piotrnar/gocoin/blob/ec4713336ba8bac5a9c0b87992cb5ef40baa4741/client/network/tick.go#L169)).  If this is right, there should be no compatibility issues with my proposed changes. **Can someone confirm this understanding?**

Thanks in advance!
Amiti

**Comment by piotrnar** [comment]
> My understanding: in response to a version message, a gocoin node will self-advertise its address (link), and often initiate a getaddr message (link). 

Yes, this is correct.

It never sends `addr` message unrequested, except of the one with own IP shortly after the version exchange.

**Comment by amitiuttarwar** [comment]
thanks for confirming! since the node self-advertises, my proposed changes would not impact the observable interactions with a bitcoin core node.

**Comment by piotrnar** [comment]
No problem.

Just one comment.
I would not say that gocoin "often" issues `getaddr` message.
I would rather use the word "sometimes" than "often" or "usually".

Gocoin node only sends `getaddr` if there are not enough peers in the database.
If the peers database has enough records (5000 or more), it does not send `getaddr`

**Comment by amitiuttarwar** [comment]
thanks for the clarification!
