### ISSUE TITLE
Getting 0 when trying to get Block.height, Txo.BlockHeight

### ISSUE THREAD

**Issue by Pandemolde** [piotrnar/gocoin#60]
I'm using the module `btc/others/blockdb` with the method `NewBlockDB("path/to/bitcoind/blocks") ` in order to retrieve data using `btc.block.NewBlock()` and I can get all values I need from each block in the blockchain correctly but the block height.

I've tried with the `block.go` module (Block.BlockExtraInfo.Height) or even with the `Tx.go` module (Tx.TxOut.BlockHeight) but nothing, I get always 0.

I've read a comment inside the `block.go` module but I don't get the point.
```
type Block struct {
	Raw               []byte
	Hash              *Uint256
	Txs               []*Tx
	TxCount, TxOffset int          // Number of transactions and byte offset to the first one
	Trusted           sys.SyncBool // if the block is trusted, we do not check signatures and some other things...
	LastKnownHeight   uint32

	BlockExtraInfo // If we cache block on disk (between downloading and comitting), this data has to be preserved

	MedianPastTime uint32 // Set in PreCheckBlock() .. last used in PostCheckBlock()

	// These flags are set in BuildTxList() used later (e.g. by script.VerifyTxScript):
	NoWitnessSize int
	BlockWeight   uint
	PaidTxsVSize  uint
	TotalInputs   int

	NoWitnessData []byte // This is set by BuildNoWitnessData()
}
```

Any help on this? Probably I'm doing something wrong... But just can't see what exactly.
Thanks in advanced!

**Comment by piotrnar** [comment]
As a general rule, there is no height in the block's data itself.
Normally you maintain the block-chain and calculate each block's height using it.
Not sure about your specific application so cannot advise on a solution.

Beginning with BIP34 enforcement, you can extract the block height from the coinbase tx, but it will not work with the early blocks (before $227931). Look for "// Enforce rule that the coinbase starts with serialised block height" in lib/chain/block_check.go to see how the value is stored inside bl.Txs[0].TxIn[0].ScriptSig.
